version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Set version update strategy
    versioning-strategy: auto
    # Allow up-to-date dependencies to be updated
    allow:
      # Allow updates for all dependencies
      - dependency-type: "all"
    # Specify the version update type that all updates will use
    ignore:
      # Ignore updates for packages with breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] 